### ISSUE TITLE
[BUG REPORT] code won't build and run

### ISSUE THREAD

**Issue by xamthor** [daisymdev/daisymurillo.com#1]
## Bug Report

**Current Behavior**
npm run build prod is not executing correctly 

**Input Code**

```js
var build=> (web) => site;
```

**Expected behavior/code**
website is suppose to launch in localhost:8080

**NPM Configuration (. package.json)**

```js
{
  "build": { "config": "prod" }
}
```

**Environment**
- Babel version(s): [e.g. v6.0.0, v7.0.0-beta.34]
- Node/npm version: [e.g. Node 8/npm 5]
- OS: [e.g. OSX 10.13.4, Windows 10]
- Monorepo: [e.g. yes/no/Lerna]
- How you are using Babel: [e.g. `cli`, `register`, `loader`]

**Possible Solution**

**Additional context/Screenshots**

**Comment by kruzus** [comment]
My coworker from Bangladesh was getting the same issue, if you find a solution please fax me! @xamthor
