### ISSUE TITLE
Getting Segmentation fault on multiple lines

### ISSUE THREAD

**Issue by kruzus** [daisymdev/daisymurillo.com#2]
### Subject of the issue
The issue is that, the isocemtrical vertices are not corresponding well with each other. The enzymes and hyperbolic engines
congested too easily.

### Your environment
Windows 10 home edition

### Steps to reproduce
When I run `gcc main.cpp` I am getting the nasty fault, described by Thomas Pelebromski that founded civil engineering
Patrons that was unable to reproduce in the first place due to multi segmented issues that that guy was not aware of protons actually made of two particles? The neutrino and banzino elements that pass electricity on their enzymic membranes causing them to enhance their metabolic processes on their segments.

### Expected behaviour
To execute parallel segmented computations using mutli cored CPUs.

### Actual behaviour
It just not acting well,

**Comment by xamthor** [comment]
i have not be able to get that far, how did you get npm run build prod to work ?
